### DISCUSSION TITLE
docker-compose with traefik

### DISCUSSION THREAD

**Discussion by mybuntu-git2** [Kozea/Radicale#1368] [Q&A general]
hi all,
I have a low memory device running radicale, https, auth none.
on iOS 16 and macOS Monterey , it keeps asking for passwords from time to time due to a known bug.
I understand I need a reverse proxy to workaround the bug.
my understanding is traefik is more lightweight than nginx and can be used.
however, I am totally illiterate about reverse proxies and really cannot start learning that right now.

is there a kind soul with a docker-compose file to share with a working traefik and radicale setup?

**Comment by ekovarski** [comment]
Pardon my spareness, just in a rush but figured I'll quickly post it before I forget for others who might come across this.

Here is my docker entry compose, I am using userfile so make sure you mount it in the traefik section, eg

```
volumes:
  - ./radicale/config/users:/auth/radicale:ro
```

The key to making traefik work was using the headerField to set X-Remote-User, then you need to set auth to type = "http_x_remote_user" in radicale config.


```
radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config:/config
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.radicale.middlewares=radicale-auth
      - traefik.http.middlewares.radicale-auth.basicauth.usersfile=/auth/radicale
      - traefik.http.middlewares.radicale-auth.basicauth.headerField=X-Remote-User
      - traefik.http.routers.radicale.rule=Host(`calendar.domain.tld`) || Host(`contacts.domain.tld`)
      - traefik.http.routers.radicale.entrypoints=websecure
      - traefik.http.routers.radicale.tls.certresolver=myresolver
      - traefik.http.services.radicale.loadBalancer.server.port=5232
```
